### ISSUE TITLE
setup methods rename to allocateMemory()

### ISSUE THREAD

**Issue by torisalvatore** [UWB-Biocomputing/Graphitti#164]
all setup methods just allocate memory. this should be reflected in the name of the function to promote clarity for the newcomers.

**Comment by VivekGandhi54** [comment]
There are setup methods for a variety of classes, should they all be called "allocateMemory", or keep the class descriptions?

setupEdges() --> allocateMemory() and setupVertices -->allocateMemory()
OR
setupEdges() --> allocateEdgeMemory() and setupVertices -->allocateVertexMemory()?

**Comment by stiber** [comment]
I would prefer a generic name that doesn't include the class name, so that we know we can just look for an `allocateMemory()` method in any class we run into. This would apply even to classes that allocate memory in their constructors — instead, have the constructors call a private or protected `allocateMemory()` method.
