### ISSUE TITLE
Fix synapseIndexMap_ creation and deletion

### ISSUE THREAD

**Issue by VivekGandhi54** [UWB-Biocomputing/Graphitti#188]
An `EdgeIndexMap` object is created and assigned to `Connections::synapseIndexMap_` at the end of every epoch and at the start of the simulation. ~~At the moment, this causes a memory leak between epochs.~~[shared_ptr destroys it when it's no longer used] It should be created in `Connections::setupConnections` and overwritten by `createEdgeIndexMap()` with each call.

~~The size of the map doesn't change~~, and `incomingEdgeCount_` keeps track of the indices used anyway.
~~Destroy `synapseIndexMap_` in the Connections destructor.~~ [shared_ptr destroys it when it's no longer used]

**Comment by VivekGandhi54** [comment]
The size of the map could be `numVertices * maxEdgesPerVertex`. Then we wouldn't have to dynamically allocate it, but there would be some redundancy.

**Comment by stiber** [comment]
I think we will have a decision soon (by end of spring 2021) regarding how we will replace the mishmash of vectors and dynamically allocated arrays. At that point, we should move to complete encapsulation of such things in a single type (maybe `valarray`), with fixed size allocation for the entire simulation duration.

This is important, because that is how things are allocated on the GPU and our approach is to have the CPU code mirror the GPU code.
