### ISSUE TITLE
Audit everywhere that a get() method is used

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#189]
We should not be getting the raw internal pointer from a smart pointer, and certainly not retain it. The only exceptions:

- When a raw pointer is needed to copy a block of memory to/from the GPU.
- For now, for serialization/deserialization, though probably that code could be cleaned up because it might support smart pointers better than raw pointers.
- Basically, only use raw pointers as local variables

**Comment by KamathScience** [comment]
Based on issue #76, we've switched from using raw pointers and `shared_ptr` to utilizing `unique_ptrs`. Furthermore, as per issue #423, we've adjusted accessor methods to return references instead of pointers, effectively addressing our concerns about passing raw internal pointers from smart pointers and avoiding unintended retention.

Marking this issue as "Closed".
