### ISSUE TITLE
Audit EdgeIndexMap usage

### ISSUE THREAD

**Issue by VivekGandhi54** [UWB-Biocomputing/Graphitti#237]
`EdgeIndexMap` used to only allocate space for `totalEdgeCount_` number of edges (edd99561907d90ce0e6065f32f8403dfd242e18c). It was recently changed so that it allocates the maximum possible space, avoiding the re-allocation process between epochs. The edges are still arranged in a compact manner, so the usage hasn't changed.

(See: `GPUModel::copySynapseIndexMapHostToDevice`)
Should the data be placed in a non-contiguous manner? GPU efficiency is a possible argument against this.

The data from the edgeIndexMap is `cudaMemcpy`-ed on and off the GPU, and it only copies `totalEdgeCount_` edges. As the edges are placed contiguously, this is no issue.

As `totalEdgeCount_` may change, this space on the GPU is freed and re-allocated each time. Is GPU memory more expensive, or should this change to accommodate the maximum number of edges?

Line 271 of `GPUModel.cu`: ` if (totalSynapseCount == 0) return;`
Is this a bug? It clearly just leaves behind dirty data. The same line was in `AllEdges::createEdgeIndexMap`, and caused seg faults with `test-tiny.xml` (See: b0ef10699617b64528d52b7ba18f35cb619ec629, issue #222).

**Comment by stiber** [comment]
This is something we would need to look at in detail. Since it impinges upon GPU performance, it will require a validated GPU version of Graphitti and careful performance analysis. Some preliminary notes:

- Generally, we design the CPU-side data structures with the GPU-side ones in mind. In effect, we design our data structures for the GPU and then just use those GPU structures on the CPU.
- Contiguous data is a big benefit on the GPU, where our performance is memory access bound. Edges are accessed when vertices write to them (relatively infrequently) and when summation points read from them (frequent). This has driven many of our design decisions.
- Freeing and reallocating space on the GPU does take time. On the other hand, allocating more space than we need may make some simulations impossible to run.

**Comment by VivekGandhi54** [comment]
Maybe we write it such that the size of the map only increases (when the number of edges increases)?
That way, the number of re-allocations on the CPU and GPU are minimized, the data is contiguous, and the space used on the GPU is limited by the smallest required size. Currently, the GPU frees and reallocated the block every time.

Again, a couple of helper methods in `EdgeIndexMap` would help. Eg: `clear()`, `resize(numEdges)`, and perhaps a `bool` to keep track of whether the map has grown since the last update.

**Comment by stiber** [comment]
OK, I think this is a good discussion that can be informative to the next lab member who will focus on GPU performance. We've let that part of the simulator languish since it's been "good enough", but now the GPU hardware and libraries have moved along enough that we should revisit it.
