### ISSUE TITLE
Asking the Factory to create a nonexistent class should generate a FATAL error

### ISSUE THREAD

**Issue by VivekGandhi54** [UWB-Biocomputing/Graphitti#270]
When the name of the class defined in the config files is wrong, the factories return nullptr, which leads to a seg fault. This should instead be a FATAL error.
This also happens when the name string is uninitialized. Variables that couldn't be initialized by `ParameterManager` should also throw FATAL errors (see issue #217 , which, given our now longer regression test times, should probably be a higher priority).

**Comment by stiber** [comment]
Good point; I'll put it in the fall 2021 project. Whoever does it should output a FATAL log output to console and then, for now, `exit()`. We can decide on exceptions later and just search for all of the exits.

**Comment by jardiamj** [comment]
All factories' `invokeCreateFunction` were removed in #352 since this added unnecessary complexity. `nullptr` is still being returned by the create methods (`createVertices`, `createEdges`, etc) which seems a reasonable returned value for invalid class types.

I see two options here. We can either catch it and bail out in the factory classes or where the objects are created; the latter might be a better option. The factories are used to create objects in the following files:
- `Connections.cpp`
- `Model.cpp`
- `Simulator.cpp`

**Comment by stiber** [comment]
I would imagine the best place is where the most knowledge about the error is, since the only thing we can do is to output an informative error message and quit.

**Comment by jardiamj** [comment]
> I would imagine the best place is where the most knowledge about the error is, since the only thing we can do is to output an informative error message and quit.

Then, it should be where the objects are created. The error message should tell us that the source of the error is the class name in the config file.

**Comment by stiber** [comment]
From conversation with @Oelgazz , the factor `createType()` method has the class name and so this is sufficient as far as information is concerned — plus it's only one place to add the needed code.

**Comment by stiber** [comment]
Since we can't currently get the Google test framework to check for an appropriate exit from the Factory method, we currently just return `nullptr`. This means we need to test the return value in the calling method (`Model::Model()`, `Layout::Layout()`, and `Connections::Connections()`), output an error message, and `exit(EXIT_FAILURE)`.
