### ISSUE TITLE
Update Sequence Diagram UMLs in Master branch

### ISSUE THREAD

**Issue by Oelgazz** [UWB-Biocomputing/Graphitti#586]
As a result of discussions in issue #377 there is a need to recheck and update the Sequence Diagram documentation.

Specifically (professor Stiber's words):

- There are two top-level .puml files: topLevelFlow.puml and graphitti.puml. Need to compare them, produce a single, correct version, and get that version linked in and displaying in the GitHub pages.

- Double-check diagrams against the code. Do the diagrams show the startup that is actually implemented in master? Any changes here would be a hotfix.

**Comment by Oelgazz** [comment]
Observations from comparing "topLevelFlow.puml" and "graphitti.puml":

Executive Summary: "graphitti.puml" is more updated and detailed, although "topLevelFlow.puml" has 'ParameterManager' and 'OperationManager' logic.
Details:
-"topLevelFlow.puml" starts the diagram with the Core object calling 'Parse Command Line', 'Set File Names', and 'Load Parameter File'. 'Parse Command Line' and 'Set File Names' involves an object called ParamContainer, which seems to no longer exist (from looking at the code it looks like it has become part of Core).
-All of this (along with both 'Load Parameters') has been replaced with 'Load Simulator Parameters' in "graphitti.puml".
-The 'setup' step in "graphitti.puml" is much more detailed than in "topLevelFlow.puml", as it includes 'model setup' details (getting and setting up all components of the simulator).
-"graphitti.puml" describes the entire program in one puml file, while "topLevelFlow.puml" splits it across multiple files. Discussions with @stiber indicates that splitting the program flow across multiple files is preferred.
-All other details currently shown in both diagrams are identical.
-Neither file has details regarding "OperationManager.executeOperation(registerGraphProperties)" nor "GraphManager.readGraph()". Both of these actions reside between "instantiate Simulator Objects" and "setup".

The current question is: Should "ParameterManager" and "OperationManager" be included in the final puml file, or should they be kept out for simplicity? This may need discussion with @KamathScience as She worked on the sequence diagrams previously.

**Comment by jardiamj** [comment]
I split the Graphitti sequence diagram into three because it would make it easier to follow the top-level sequence, and then put the details of certain parts in a different diagram for people to look at those details if needed. I probably didn't include details of the setup step to keep it short.

The classes such as `GraphManager` and `InputManager` didn't exist at that time hence why those `OperationManager` 's actions are not in there. Another big change, introduced by @KamathScience, is that the multiple factories were reduced to only one factory that can handle the creation of various types of objects (vertices, edges, layouts, connections, recorders).
