### ISSUE TITLE
Update Sequence Diagrams in development branch

### ISSUE THREAD

**Issue by Oelgazz** [UWB-Biocomputing/Graphitti#587]
After issue #586 is completed, the same needs to be repeated for the development branch. First, the changes done in the master branch needs to be carried over to the development branch. Then, the diagrams need to be compared with the code in the development branch and edited to ensure that they are up to date.

**Comment by stiber** [comment]
I don't think it needs to be repeated. I think that there is a way to also merge the hot fix branch into development. Since this is documentation, it would be hard to break development (though not impossible). One approach might be to create a feature branch from development, merge the hotfix branch into that, then issue a PR to do all the checks. We should talk and walk through this.
